#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2020 World Wide Technology, LLC
#      All rights reserved.
#
#      author: Joel W. King, World Wide Technology
#
#      Retrieve policy from Tetration and publish it to the PSM as an App
#
#      usage: 
#              
#             To only execute the Tetration portion of the playbook
#
#               ./tetration_app.yml -v --tags tetration --ask-vault-pass
#             
#             When you have connectivity to a Tetration for demonstration purpose
#
#               ./tetration_app.yml -v --ask-vault-pass \
#                                    -e 'api_credentials=/home/administrator/ansible/playbooks/files/tetration/api_credentials.json' \
#                                        'app_name="Wordpress-cl3" app_version=latest'
#
#             To demo pushing a policy from disk to the PSM
#  
#               ./tetration_app.yml -v --skip-tags tetration --ask-vault-pass
#  
#
- hosts: localhost
  gather_facts: no
  connection: local

  vars_files:
    - '{{ playbook_dir }}/files/passwords.yml'                  #  Credentials for PSM defined in vaulted file
    - '{{ playbook_dir }}/files/tetration/gui_credentials.yml'  #  Vault if you wish, nothing to see here

  vars:
    app_name: 'PolicyPubApp'
    app_version: latest
    api_credentials: '{{ playbook_dir }}/files/tetration/api_credentials.json'
    policy_name: DEMO
    #
    #  No variables changes below this line
    #  ------------------------------------
    proto_ports: []

  collections:
    - joelwking.pensando

  module_defaults:
    app:
      hostname: '{{ pensando_psm.host }}'
      username: '{{ pensando_psm.username }}'
      password: '{{ pensando_psm.password }}'
      api_version: v1
      tenant: default
      namespace: default

    network_security_policy:
      hostname: '{{ pensando_psm.host }}'
      username: '{{ pensando_psm.username }}'
      password: '{{ pensando_psm.password }}'
      api_version: v1
      tenant: default
      namespace: default

  tasks:
    - name: For demonstraton purposes, when a Tetration is available, query and write policy to disk
      block:
        - name: Query policy using the API via Tetration Application module
          tetration_application:
            application: '{{ app_name }}'
            version: '{{ app_version }}'
            api_host: '{{ atc_tetration.host }}'
            api_cfile: '{{ api_credentials }}'
            api_verify: False
          register: api

        - name: Write app policy to a file for future reference
          copy: 
            content: '{{ api.ansible_facts | to_nice_json(indent=2) }}' 
            dest: '{{ playbook_dir }}/files/{{ app_name }}.json'

      tags: [tetration]

    - name: Read Tetration policy from disk
      set_fact: 
        api: "{{ lookup('file', '{{ playbook_dir }}/files/{{ app_name }}.json' ) }}"

    - name: Create list of protocols and ports
      set_fact:
        proto_ports: "{{ proto_ports + [ item['proto-ports'] ] }}"
      loop: '{{ api.adm.policy }}'
      when:
        - item["confidence"] >= 0.90                       # example of selecting a subset based on confidence
        - item["action"] == "ALLOW"                        # there is an implicit DENY                    
        # - item["consumer_filter_name"] == "EPG-DEV-PUBWIN1:EPG-DEV"

    - name: Delete Policy  
      network_security_policy:
        state: absent
        policy_name: '{{ policy_name }}'
      tags: [bind]

    - name: Delete app  
      app:
        state: absent
        app_name: '{{ app_name }}_{{ app_version }}'

    - name: Add app
      app:
          state: present
          app_name: '{{ app_name }}_{{ app_version }}'
          proto_ports: '{{ proto_ports }}'

    - name: Report App name and version from data
      debug:
        msg: 'App Name: {{ api.adm.raw.name }} version: {{ api.adm.raw.version }} latest: {{ api.adm.raw.latest_adm_version }}'

    - name: Add a network_security_policy which references the app
      network_security_policy:
          state: present
          policy_name: '{{ policy_name }}'
          rules:
            - apps:
                - '{{ app_name }}_{{ app_version }}'
              action: permit
              from-ip-addresses: 
                - 198.51.100.0/24
              to-ip-addresses:
                - 192.0.2.0/24
            - proto-ports: 
                - protocol: udp
                  ports: '123'
              action: permit
              from-ip-addresses: 
                - 198.18.0.0/15
              to-ip-addresses: 
                - 198.18.0.0/15
      tags: [bind]