#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2020 World Wide Technology, LLC
#      All rights reserved.
#
#      author: Joel W. King, World Wide Technology
#
#      Retrieve policy from Tetration and publish it to the PSM as an App
#
#      usage: ./tetration_app.yml -v --tags tetration
#                                    --skip-tags debug
#
#  
- hosts: localhost
  gather_facts: no
  connection: local

  vars_files:
    - /home/administrator/ansible/playbooks/files/passwords.yml   #  Credentials for PSM defined in vaulted file

  vars:
    app_name: 'PolicyPubApp'
    app_version: latest
    api_credentials: /home/administrator/ansible/playbooks/files/tetration/api_credentials.json
    #
    #  No variables changes below this line
    #  ------------------------------------
    proto_ports: []

  collections:
    - joelwking.pensando

  module_defaults:
    app:
      hostname: '{{ pensando_psm.host }}'
      username: '{{ pensando_psm.username }}'
      password: '{{ pensando_psm.password }}'
      api_version: v1
      tenant: default
      namespace: default

  tasks:
    - name: Query policy using the API via Tetration Application module
      tetration_application:
        application: '{{ app_name }}'
        version: '{{ app_version }}'
        api_host: '{{ atc_tetration.host }}'
        api_cfile: '{{ api_credentials }}'
        api_verify: False
      register: api
      tags: [tetration]

    - debug:
        msg: "{{ item['proto-ports'] }}"
      loop: '{{ api.ansible_facts.adm.policy }}'

    - name: Create list of protocols and ports
      set_fact:
        # proto_ports: "{{ proto_ports + [ {'protocol': item['proto-ports'].protocol, 'ports': item['proto-ports'].ports } ] }}"
        proto_ports: "{{ proto_ports + [ item['proto-ports'] ] }}"
      loop: '{{ api.ansible_facts.adm.policy }}'
      when:
        # - item["confidence"] >= 0.90
        # - item["provider_filter_name"] == "EPG-DEV-PUBWIN1"
        # - item["consumer_filter_name"] == "EPG-DEV-PUBWIN1:EPG-DEV"
        # - item["confidence"] >= 0.90

    - name: Delete app  
      app:
        state: absent
        app_name: '{{ app_name }}_{{ app_version }}'

    - name: Add app
      app:
          state: present
          app_name: '{{ app_name }}_{{ app_version }}'
          proto_ports: '{{ proto_ports }}'

    #
    #  All Finished!
    #